version: '3.0.0'
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: nestdb
    volumes:
      - ./data:/var/lib/postgresql/data
